In [1]:
import numpy as np
from scipy.spatial.distance import pdist, squareform


In [2]:

# Definir la señal que usas en Go
signal_py = np.array([[0.0, 0.0], [1.0, 1.0], [0.0, 1.0], [1.0, 0.0]])

# Calcular PdistSqEuclidean
K_condensed = pdist(signal_py, metric="sqeuclidean")
print(f"K_condensed (pdist): {K_condensed}") # Esto debería ser [2. 1. 1. 1. 1. 2.]

# Definir gamma
gamma = 1.0

# Aplicar gamma
K_scaled = K_condensed * gamma
print(f"K_scaled (after gamma): {K_scaled}")

# Aplicar clipping (usando los mismos límites que en Go: 0.0, 1e2)
K_clipped = np.clip(K_scaled, 0.0, 1e2)
print(f"K_clipped: {K_clipped}") # Esto debería seguir siendo [2. 1. 1. 1. 1. 2.]

# Convertir a squareform y aplicar exponencial
gram_matrix = np.exp(squareform(-K_clipped))
print(f"Gram Matrix (full):\n{gram_matrix}")

# Ahora, calcular el costo para el segmento [1:4]
start = 1
end = 4
sub_gram = gram_matrix[start:end, start:end]
print(f"Sub-Gram Matrix for [{start}:{end}]:\n{sub_gram}")

diag_sum = np.diagonal(sub_gram).sum()
total_sum = sub_gram.sum()
segment_len = end - start

cost_val = diag_sum - (total_sum / segment_len)
print(f"Calculated Cost for [{start}:{end}]: {cost_val}")

K_condensed (pdist): [2. 1. 1. 1. 1. 2.]
K_scaled (after gamma): [2. 1. 1. 1. 1. 2.]
K_clipped: [2. 1. 1. 1. 1. 2.]
Gram Matrix (full):
[[1.         0.13533528 0.36787944 0.36787944]
 [0.13533528 1.         0.36787944 0.36787944]
 [0.36787944 0.36787944 1.         0.13533528]
 [0.36787944 0.36787944 0.13533528 1.        ]]
Sub-Gram Matrix for [1:4]:
[[1.         0.36787944 0.36787944]
 [0.36787944 1.         0.13533528]
 [0.36787944 0.13533528 1.        ]]
Calculated Cost for [1:4]: 1.419270556280335


In [3]:
diag_sum_py = np.diagonal(sub_gram).sum()
total_sum_py = sub_gram.sum()
print(f"Python diag_sum: {diag_sum_py}")
print(f"Python total_sum: {total_sum_py}")

Python diag_sum: 3.0
Python total_sum: 4.742188331158995
